apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:               
      app: nginx
  template:
    metadata:
      labels:                  
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  namespace: nginx
  name: nginx
spec:
  selector:                     
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: NodePort

