apiVersion: v1
kind: Namespace
metadata:
  name: nginx
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx
  name: nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  namespace: nginx
  name: nginx
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx

