apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: enable_cert_manager
              operator: In
              values: ["true"]
            - key: environment
              operator: In
              values: ["dev", "prod"]     
  template:
    metadata:
      name: 'cert-manager'
    spec:
      project: default
      source:
        chart: cert-manager
        repoURL: https://charts.jetstack.io
        targetRevision: 1.17.1
        helm:
          values: |
            installCRDs: true
      destination:
        server: https://kubernetes.default.svc  # Add this line to specify the destination server
        namespace: cert-manager
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # This handles large CRDs
        
