apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: dev
  template:
    metadata:
      name: 'cert-manager'
    spec:
      project: default
      source:
        chart: cert-manager
        repoURL: https://charts.jetstack.io
        targetRevision: 1.17.1
        helm:
          values: |
            installCRDs: true
            securityContext:
              fsGroup: 1001
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
      destination:
        server: https://kubernetes.default.svc  # Add this line to specify the destination server
        namespace: cert-manager
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # This handles large CRDs
        
