apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false  
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: enable_kube_prometheus_stack
              operator: In
              values: ["true"]
            - key: environment
              operator: In
              values: ["dev", "prod"]  
  template:
    metadata:
      name: 'kube-prometheus-stack'
    spec:
      project: default
      source:
        chart: kube-prometheus-stack
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: 55.4.0
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc  # Add this line to specify the destination server
        namespace: monitoring
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # This handles large CRDs
        
