apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Ensure this syncs earlier than other applications
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    # Try an older version with smaller CRD annotations to avoid the size limit issue
    targetRevision: 55.4.0
    helm:
      values: |
        # CRD management settings
        crds:
          create: true
          keep: false
        
        # Disable admission webhooks to avoid issues on Kind
        prometheusOperator:
          admissionWebhooks:
            enabled: false
            failurePolicy: Ignore
          tls:
            enabled: false
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          
          # Critical setting: install CRDs before components
          manageCRDs: true
        
        alertmanager:
          enabled: true
          alertmanagerSpec:
            replicas: 1
            resources:
              limits:
                cpu: 50m
                memory: 64Mi
              requests:
                cpu: 25m
                memory: 32Mi
        
        grafana:
          enabled: true
          adminPassword: prom-operator
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
              
        prometheus:
          enabled: true
          prometheusSpec:
            replicas: 1
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
        
        # Reduce resources for other components
        kube-state-metrics:
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
        
        nodeExporter:
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-prometheus-stack
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # These options are critical for handling CRDs properly
      - ServerSideApply=true
      - Replace=true
      - Force=true