apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 55.4.0
    helm:
      values: |
        # CRD management settings
        crds:
          create: true
          keep: false
        
        # Disable admission webhooks to avoid issues on Kind
        prometheusOperator:
          admissionWebhooks:
            enabled: false
            failurePolicy: Ignore
          tls:
            enabled: false
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          
          # Critical setting: install CRDs before components
          manageCRDs: true
        
        alertmanager:
          enabled: true
          alertmanagerSpec:
            replicas: 1
            resources:
              limits:
                cpu: 50m
                memory: 64Mi
              requests:
                cpu: 25m
                memory: 32Mi
        
        grafana:
          enabled: true
          adminPassword: prom-operator
          # Adjust Grafana resource limits - the default might be too restrictive
          resources:
            limits:
              cpu: 200m        # Increased from 100m
              memory: 256Mi    # Increased from 128Mi
            requests:
              cpu: 100m        # Increased from 50m
              memory: 128Mi    # Increased from 64Mi
          # Add startup probe to give Grafana more time to initialize
          startupProbe:
            enabled: true
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
          # Modify readiness probe to be more lenient
          readinessProbe:
            enabled: true
            failureThreshold: 3
            timeoutSeconds: 5
            periodSeconds: 15
          # Modify liveness probe
          livenessProbe:
            enabled: true
            failureThreshold: 10
            timeoutSeconds: 5
            periodSeconds: 15
          # Add extra initialization time
          initChownData:
            enabled: true
            resources:
              limits:
                cpu: 50m
                memory: 64Mi
          # Ensure Grafana has permissions to write to its directories
          securityContext:
            runAsUser: 472
            runAsGroup: 472
            fsGroup: 472
              
        prometheus:
          enabled: true
          prometheusSpec:
            replicas: 1
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
        
        # Reduce resources for other components
        kube-state-metrics:
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
        
        nodeExporter:
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-prometheus-stack
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - Force=true