apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: longhorn
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: dev
  template:
    metadata:
      name: 'longhorn'
    spec:
      project: default
      source:
        chart: longhorn
        repoURL: https://charts.longhorn.io 
        targetRevision: 1.8.1
        helm:
          values: |
            serviceAccount:
              create: true
              name: longhorn-service-account        
      destination:
        server: https://kubernetes.default.svc  # Add this line to specify the destination server
        namespace: longhorn-system
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # This handles large CRDs
        
