apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: dev
  template:
    metadata:
      name: 'metrics-server'
    spec:
      project: default
      source:
        chart: metrics-server
        repoURL: https://kubernetes-sigs.github.io/metrics-server/
        targetRevision: 3.12.2
      destination:
        server: https://kubernetes.default.svc  # Add this line to specify the destination server
        namespace: kube-system
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # This handles large CRDs
        
