apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: enable_metrics_server
              operator: In
              values: ["true"]
            - key: environment
              operator: In
              values: ["dev", "prod"]  # Matches either dev or prod
  template:
    metadata:
      name: 'metrics-server'
    spec:
      project: default
      source:
        chart: metrics-server
        repoURL: https://kubernetes-sigs.github.io/metrics-server/
        targetRevision: 3.12.2
      destination:
        server: https://kubernetes.default.svc  # Ensures it deploys to the correct cluster
        namespace: kube-system
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # This handles large CRDs

