apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: dev
  template:
    metadata:
      name: 'nginx'
    spec:
      project: default
      source:
        chart: nginx
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: "19.0.1"
      destination:
        server: https://kubernetes.default.svc  # Add this line to specify the destination server
        namespace: nginx
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # This handles large CRDs
        
