apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: ubuntu:latest
        command: ["/bin/sh", "-c"]
        args:
          - mkdir -p /var/www && 
            echo '<h1>Hello, World!</h1><p>Welcome to my Ubuntu-based server.</p>' > /var/www/index.html && 
            apt update && apt install -y python3 && 
            python3 -m http.server 8080 --directory /var/www
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort  # Change to LoadBalancer if needed

